use_frameworks!

platform :ios, '8.0'

target 'TRULogining_Example' do
  pod 'TRULogining', :path => '../'
  #由于依赖的TRUNetworking在更上一层的文件中，所以需要../../
  pod 'TRUNetworking', :path => '../../TRUNetworking'
  target 'TRULogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
